Codigo Fonte/StarCastTime1/Web.Mvc/Controllers/LoginMedicoController.cs
using Infra.Data.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Mvc.Controllers
{
    public class LoginMedicoController : Controller
    {

        private StarCastDBContex db = new StarCastDBContex();
        string MedicosId;

        // GET: LoginMedico
        public ActionResult Index()
        {

            ViewBag.MedicosId = new SelectList
                (
                   db.Medicos.ToList(), "Id", "Nome", MedicosId
                );


            return View();
        }
        [HttpPost]
        public ActionResult Index(string MedicosId)
        {
            Session["IdMedico"] = MedicosId;
            Session["Perfil"] = 2;
            return RedirectToAction("Index","Agendamentoes");
        }
    }
}

Codigo Fonte/StarCastTime1/Web.Mvc/Views/LoginMedico/Index.cshtml
@model Core.Base.Entities.Medico

@{
    ViewBag.Title = "View";
}
@using (Html.BeginForm("Index", "LoginMedico", FormMethod.Post))
{
    <h2>Login Medicos</h2>

    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>
            <dd>
                @Html.DropDownList("MedicosId", String.Empty)
            </dd>
            <br />
            <dt>
                @Html.DisplayNameFor(model => model.Senha)
            </dt>
            <dd>
                @Html.PasswordFor(model => model.Senha)
            </dd>
        </dl>
    </div>
    <p>
        <input type="submit" value="Logar" class="btn btn-default" />

        @*@Html.ActionLink("Login", "Login", new { id = Model.Id }) |*@
    </p>
}