Codigo Fonte/StarCastTime1/Web.Mvc/Controllers/LoginPacienteController.cs
using Infra.Data.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Mvc.Controllers
{
    public class LoginPacienteController : Controller
    {

        private StarCastDBContex db = new StarCastDBContex();
        string PacienteId;
        // GET: LoginPaciente
        public ActionResult Index()
        {

            ViewBag.PacientesId = new SelectList
                (
                   db.Pacientes.ToList(), "Id", "Nome", PacienteId
                );


            return View();
        }
        [HttpPost]
        public ActionResult Index(string PacienteId)
        {
            Session["IdMedico"] = PacienteId;
            Session["Perfil"] = 1;
            return RedirectToAction("Index", "Agendamentoes");
        }
    }
}

Codigo Fonte/StarCastTime1/Web.Mvc/Views/LoginPaciente/Index.cshtml
@model Core.Base.Entities.Paciente

@{
    ViewBag.Title = "View";
}
@using (Html.BeginForm("Index", "LoginPaciente", FormMethod.Post))
{
    <h2>Login Medicos</h2>

    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>
            <dd>
                @Html.DropDownList("PacientesId", String.Empty)
            </dd>
            <br />
            <dt>
                @Html.DisplayNameFor(model => model.Senha)
            </dt>
            <dd>
                @Html.PasswordFor(model => model.Senha)
            </dd>
        </dl>
    </div>
    <p>
        <input type="submit" value="Logar" class="btn btn-default" />

        @*@Html.ActionLink("Login", "Login", new { id = Model.Id }) |*@
    </p>
}